export const CP_BATCHES = [
  {
    id:"cpb1", name:"Q1 2026 Graduate Intake", status:"Active",
    candidates:48, services:6, flagged:2,
    tasksComplete:312, tasksTotal:480, started:"15 Feb 2026",
    serviceCards:[
      { name:"NIN Verification",       complete:48, total:48, flagged:0, status:"Complete"    },
      { name:"Employment Reference",   complete:32, total:48, flagged:2, status:"In Progress" },
      { name:"Academic Verification",  complete:24, total:48, flagged:0, status:"In Progress" },
      { name:"Address Verification",   complete:8,  total:48, flagged:0, status:"In Progress" },
      { name:"Guarantor Verification", complete:48, total:48, flagged:0, status:"Complete"    },
      { name:"Criminal Check",         complete:0,  total:48, flagged:0, status:"Pending"     },
    ],
  },
  {
    id:"cpb2", name:"Executive Hires Feb", status:"Active",
    candidates:7, services:8, flagged:0,
    tasksComplete:42, tasksTotal:56, started:"10 Feb 2026",
    serviceCards:[
      { name:"NIN Verification",              complete:7, total:7, flagged:0, status:"Complete"    },
      { name:"Employment Reference",          complete:7, total:7, flagged:0, status:"Complete"    },
      { name:"Academic Verification",         complete:6, total:7, flagged:0, status:"In Progress" },
      { name:"Address Verification",          complete:7, total:7, flagged:0, status:"Complete"    },
      { name:"Criminal Check",                complete:6, total:7, flagged:0, status:"In Progress" },
      { name:"Professional Membership",       complete:5, total:7, flagged:0, status:"In Progress" },
      { name:"Guarantor Verification",        complete:4, total:7, flagged:0, status:"In Progress" },
      { name:"Reference Check",               complete:0, total:7, flagged:0, status:"Pending"     },
    ],
  },
  {
    id:"cpb3", name:"Contract Staff Wave 3", status:"Ready",
    candidates:45, services:4, flagged:0,
    tasksComplete:180, tasksTotal:180, started:"01 Feb 2026",
    serviceCards:[
      { name:"NIN Verification",      complete:45, total:45, flagged:0, status:"Complete" },
      { name:"Employment Reference",  complete:45, total:45, flagged:0, status:"Complete" },
      { name:"Address Verification",  complete:45, total:45, flagged:0, status:"Complete" },
      { name:"Criminal Check",        complete:45, total:45, flagged:0, status:"Complete" },
    ],
  },
  {
    id:"cpb4", name:"IT Department Backfill", status:"Pending",
    candidates:16, services:6, flagged:0,
    tasksComplete:0, tasksTotal:96, started:"28 Feb 2026",
    serviceCards:[
      { name:"NIN Verification",      complete:0, total:16, flagged:0, status:"Pending" },
      { name:"Employment Reference",  complete:0, total:16, flagged:0, status:"Pending" },
      { name:"Academic Verification", complete:0, total:16, flagged:0, status:"Pending" },
      { name:"Address Verification",  complete:0, total:16, flagged:0, status:"Pending" },
      { name:"Criminal Check",        complete:0, total:16, flagged:0, status:"Pending" },
      { name:"Reference Check",       complete:0, total:16, flagged:0, status:"Pending" },
    ],
  },
];

export const CP_DELIVERED_BATCHES = [
  { id:"cpd1", name:"Contract Staff Wave 2", candidates:45,  delivered:"28 Feb 2026" },
  { id:"cpd2", name:"IT Hires January",      candidates:12,  delivered:"15 Feb 2026" },
  { id:"cpd3", name:"Q4 2025 Graduate Intake",candidates:120,delivered:"18 Jan 2026" },
  { id:"cpd4", name:"Executive Search Dec",  candidates:8,   delivered:"22 Dec 2025" },
  { id:"cpd5", name:"Operations Staff Q4",   candidates:35,  delivered:"10 Dec 2025" },
];

export const CP_SERVICE_TASKS = {
  "cpb1-NIN Verification": {
    released: false,
    tasks: [
      { candidate:"John Doe",     employer:"—", status:"Complete",   flagged:false, result:{ outcome:"Verified", positionClaimed:"NIN: 12345678901", positionVerified:"NIN: 12345678901", periodClaimed:"—", periodVerified:"—", contact:"NIMC Portal", verifiedOn:"16 Feb 2026", notes:"NIN verified successfully against NIMC database." } },
      { candidate:"Jane Smith",   employer:"—", status:"Complete",   flagged:false, result:{ outcome:"Verified", positionClaimed:"NIN: 23456789012", positionVerified:"NIN: 23456789012", periodClaimed:"—", periodVerified:"—", contact:"NIMC Portal", verifiedOn:"16 Feb 2026", notes:"NIN verified successfully." } },
      { candidate:"Mike Brown",   employer:"—", status:"Complete",   flagged:false, result:{ outcome:"Verified", positionClaimed:"NIN: 34567890123", positionVerified:"NIN: 34567890123", periodClaimed:"—", periodVerified:"—", contact:"NIMC Portal", verifiedOn:"16 Feb 2026", notes:"NIN verified successfully." } },
      { candidate:"Sarah Green",  employer:"—", status:"Complete",   flagged:false, result:{ outcome:"Verified", positionClaimed:"NIN: 45678901234", positionVerified:"NIN: 45678901234", periodClaimed:"—", periodVerified:"—", contact:"NIMC Portal", verifiedOn:"17 Feb 2026", notes:"NIN verified successfully." } },
      { candidate:"Peter Obi",    employer:"—", status:"Complete",   flagged:false, result:{ outcome:"Verified", positionClaimed:"NIN: 56789012345", positionVerified:"NIN: 56789012345", periodClaimed:"—", periodVerified:"—", contact:"NIMC Portal", verifiedOn:"17 Feb 2026", notes:"NIN verified successfully." } },
      { candidate:"Grace Lee",    employer:"—", status:"Complete",   flagged:false, result:{ outcome:"Verified", positionClaimed:"NIN: 67890123456", positionVerified:"NIN: 67890123456", periodClaimed:"—", periodVerified:"—", contact:"NIMC Portal", verifiedOn:"17 Feb 2026", notes:"NIN verified successfully." } },
      { candidate:"David Ade",    employer:"—", status:"Complete",   flagged:false, result:{ outcome:"Verified", positionClaimed:"NIN: 78901234567", positionVerified:"NIN: 78901234567", periodClaimed:"—", periodVerified:"—", contact:"NIMC Portal", verifiedOn:"18 Feb 2026", notes:"NIN verified successfully." } },
      { candidate:"Mary Johnson", employer:"—", status:"Complete",   flagged:false, result:{ outcome:"Verified", positionClaimed:"NIN: 89012345678", positionVerified:"NIN: 89012345678", periodClaimed:"—", periodVerified:"—", contact:"NIMC Portal", verifiedOn:"18 Feb 2026", notes:"NIN verified successfully." } },
    ],
  },
  "cpb1-Guarantor Verification": {
    released: false,
    tasks: [
      { candidate:"John Doe",     employer:"Mr. Ade Bello",   status:"Complete", flagged:false, result:{ outcome:"Verified", positionClaimed:"Guarantor: Mr. Ade Bello", positionVerified:"Confirmed", periodClaimed:"—", periodVerified:"—", contact:"08012345678", verifiedOn:"19 Feb 2026", notes:"Guarantor confirmed candidate's identity and good standing." } },
      { candidate:"Jane Smith",   employer:"Mrs. Ngozi Obi",  status:"Complete", flagged:false, result:{ outcome:"Verified", positionClaimed:"Guarantor: Mrs. Ngozi Obi", positionVerified:"Confirmed", periodClaimed:"—", periodVerified:"—", contact:"08023456789", verifiedOn:"19 Feb 2026", notes:"Guarantor verified." } },
      { candidate:"Mike Brown",   employer:"Mr. Kola Ade",    status:"Complete", flagged:false, result:{ outcome:"Verified", positionClaimed:"Guarantor: Mr. Kola Ade", positionVerified:"Confirmed", periodClaimed:"—", periodVerified:"—", contact:"08034567890", verifiedOn:"20 Feb 2026", notes:"Guarantor verified." } },
      { candidate:"Sarah Green",  employer:"Dr. Emeka Nwose", status:"Complete", flagged:false, result:{ outcome:"Verified", positionClaimed:"Guarantor: Dr. Emeka Nwose", positionVerified:"Confirmed", periodClaimed:"—", periodVerified:"—", contact:"08045678901", verifiedOn:"20 Feb 2026", notes:"Guarantor verified." } },
      { candidate:"Peter Obi",    employer:"Mr. Tunde Sule",  status:"Complete", flagged:false, result:{ outcome:"Verified", positionClaimed:"Guarantor: Mr. Tunde Sule", positionVerified:"Confirmed", periodClaimed:"—", periodVerified:"—", contact:"08056789012", verifiedOn:"20 Feb 2026", notes:"Guarantor verified." } },
      { candidate:"Grace Lee",    employer:"Mrs. Bisi Ojo",   status:"Complete", flagged:false, result:{ outcome:"Verified", positionClaimed:"Guarantor: Mrs. Bisi Ojo", positionVerified:"Confirmed", periodClaimed:"—", periodVerified:"—", contact:"08067890123", verifiedOn:"21 Feb 2026", notes:"Guarantor verified." } },
      { candidate:"David Ade",    employer:"Mr. Chidi Eze",   status:"Complete", flagged:false, result:{ outcome:"Verified", positionClaimed:"Guarantor: Mr. Chidi Eze", positionVerified:"Confirmed", periodClaimed:"—", periodVerified:"—", contact:"08078901234", verifiedOn:"21 Feb 2026", notes:"Guarantor verified." } },
      { candidate:"Mary Johnson", employer:"Mr. Seun Lawal",  status:"Complete", flagged:false, result:{ outcome:"Verified", positionClaimed:"Guarantor: Mr. Seun Lawal", positionVerified:"Confirmed", periodClaimed:"—", periodVerified:"—", contact:"08089012345", verifiedOn:"21 Feb 2026", notes:"Guarantor verified." } },
    ],
  },
  "cpb1-Employment Reference": {
    released: false,
    tasks: [
      { candidate:"John Doe",     employer:"Acme Corporation",  status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"Software Engineer", positionVerified:"Software Engineer", periodClaimed:"Jan 2021 – Dec 2024", periodVerified:"Jan 2021 – Dec 2024", contact:"Jane HR (jane@acme.ng)", verifiedOn:"20 Feb 2026", notes:"Employment confirmed with positive reference." } },
      { candidate:"Jane Smith",   employer:"Beta Industries",   status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"Marketing Executive", positionVerified:"Marketing Executive", periodClaimed:"Mar 2020 – Nov 2024", periodVerified:"Mar 2020 – Nov 2024", contact:"HR Dept (hr@beta.ng)", verifiedOn:"20 Feb 2026", notes:"All details confirmed." } },
      { candidate:"Mike Brown",   employer:"Gamma Holdings",    status:"Flagged",    flagged:true,  result:null,
        discrepancy:{ issue:"Job title mismatch", claimed:"Senior Manager", confirmed:"Manager (not Senior)", contact:"Bob HR (bob@gamma.ng)", verifiedOn:"22 Feb 2026" } },
      { candidate:"Sarah Green",  employer:"Delta Corp",        status:"In Progress",flagged:false, result:null },
      { candidate:"Peter Obi",    employer:"Echo Limited",      status:"In Progress",flagged:false, result:null },
      { candidate:"Grace Lee",    employer:"—",                 status:"Pending",    flagged:false, result:null },
      { candidate:"David Ade",    employer:"Foxtrot Inc",       status:"Flagged",    flagged:true,  result:null,
        discrepancy:{ issue:"Period mismatch", claimed:"Jan 2020 – Dec 2023", confirmed:"Jun 2021 – Dec 2023", contact:"HR Team (hr@foxtrot.ng)", verifiedOn:"21 Feb 2026" } },
      { candidate:"Mary Johnson", employer:"Golf Services",     status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"Accountant", positionVerified:"Accountant", periodClaimed:"Apr 2019 – Jan 2025", periodVerified:"Apr 2019 – Jan 2025", contact:"Finance HR (hr@golf.ng)", verifiedOn:"21 Feb 2026", notes:"Confirmed." } },
    ],
  },
  "cpb1-Academic Verification": {
    released: false,
    tasks: [
      { candidate:"John Doe",     employer:"University of Lagos",   status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"B.Sc Computer Science", positionVerified:"B.Sc Computer Science", periodClaimed:"2015 – 2019", periodVerified:"2015 – 2019", contact:"Registry (registry@unilag.edu.ng)", verifiedOn:"21 Feb 2026", notes:"Degree confirmed with First Class." } },
      { candidate:"Jane Smith",   employer:"Lagos State University", status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"B.Sc Business Administration", positionVerified:"B.Sc Business Administration", periodClaimed:"2016 – 2020", periodVerified:"2016 – 2020", contact:"Examinations Office (exams@lasu.edu.ng)", verifiedOn:"21 Feb 2026", notes:"Degree confirmed." } },
      { candidate:"Mike Brown",   employer:"University of Ibadan",  status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"B.Sc Economics", positionVerified:"B.Sc Economics", periodClaimed:"2014 – 2018", periodVerified:"2014 – 2018", contact:"Registry (registry@ui.edu.ng)", verifiedOn:"22 Feb 2026", notes:"Degree confirmed." } },
      { candidate:"Sarah Green",  employer:"Covenant University",   status:"In Progress",flagged:false, result:null },
      { candidate:"Peter Obi",    employer:"ABU Zaria",             status:"In Progress",flagged:false, result:null },
      { candidate:"Grace Lee",    employer:"—",                     status:"Pending",    flagged:false, result:null },
      { candidate:"David Ade",    employer:"—",                     status:"Pending",    flagged:false, result:null },
      { candidate:"Mary Johnson", employer:"OAU Ile-Ife",           status:"In Progress",flagged:false, result:null },
    ],
  },
  "cpb1-Address Verification": {
    released: false,
    tasks: [
      { candidate:"John Doe",     employer:"12 Adeyemi St, Lagos",     status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"12 Adeyemi St, Surulere, Lagos", positionVerified:"12 Adeyemi St, Surulere, Lagos", periodClaimed:"—", periodVerified:"—", contact:"Field Agent: Emeka O.", verifiedOn:"22 Feb 2026", notes:"Address confirmed. Candidate resides at stated address." } },
      { candidate:"Jane Smith",   employer:"5 Bode Thomas, Lagos",     status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"5 Bode Thomas, Surulere, Lagos", positionVerified:"5 Bode Thomas, Surulere, Lagos", periodClaimed:"—", periodVerified:"—", contact:"Field Agent: Kemi A.", verifiedOn:"22 Feb 2026", notes:"Address confirmed." } },
      { candidate:"Mike Brown",   employer:"44 Allen Ave, Ikeja",      status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"44 Allen Ave, Ikeja, Lagos", positionVerified:"44 Allen Ave, Ikeja, Lagos", periodClaimed:"—", periodVerified:"—", contact:"Field Agent: Tunde B.", verifiedOn:"23 Feb 2026", notes:"Address confirmed." } },
      { candidate:"Sarah Green",  employer:"22 Victoria Island, Lagos",status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"22 Adeola Odeku, V/I, Lagos", positionVerified:"22 Adeola Odeku, V/I, Lagos", periodClaimed:"—", periodVerified:"—", contact:"Field Agent: Ngozi C.", verifiedOn:"23 Feb 2026", notes:"Address confirmed." } },
      { candidate:"Peter Obi",    employer:"8 Oba Akran, Ikeja",       status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"8 Oba Akran Ave, Ikeja, Lagos", positionVerified:"8 Oba Akran Ave, Ikeja, Lagos", periodClaimed:"—", periodVerified:"—", contact:"Field Agent: Emeka O.", verifiedOn:"24 Feb 2026", notes:"Address confirmed." } },
      { candidate:"Grace Lee",    employer:"—",                        status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"3 Opebi Road, Ikeja, Lagos", positionVerified:"3 Opebi Road, Ikeja, Lagos", periodClaimed:"—", periodVerified:"—", contact:"Field Agent: Kemi A.", verifiedOn:"24 Feb 2026", notes:"Address confirmed." } },
      { candidate:"David Ade",    employer:"—",                        status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"19 Oregun Road, Ikeja, Lagos", positionVerified:"19 Oregun Road, Ikeja, Lagos", periodClaimed:"—", periodVerified:"—", contact:"Field Agent: Tunde B.", verifiedOn:"25 Feb 2026", notes:"Address confirmed." } },
      { candidate:"Mary Johnson", employer:"—",                        status:"Complete",   flagged:false,
        result:{ outcome:"Verified", positionClaimed:"7 Ikorodu Road, Lagos", positionVerified:"7 Ikorodu Road, Lagos", periodClaimed:"—", periodVerified:"—", contact:"Field Agent: Ngozi C.", verifiedOn:"25 Feb 2026", notes:"Address confirmed." } },
    ],
  },
  "cpb1-Criminal Check": {
    released: false,
    tasks: [
      { candidate:"John Doe",     employer:"—", status:"Pending", flagged:false, result:null },
      { candidate:"Jane Smith",   employer:"—", status:"Pending", flagged:false, result:null },
      { candidate:"Mike Brown",   employer:"—", status:"Pending", flagged:false, result:null },
      { candidate:"Sarah Green",  employer:"—", status:"Pending", flagged:false, result:null },
      { candidate:"Peter Obi",    employer:"—", status:"Pending", flagged:false, result:null },
      { candidate:"Grace Lee",    employer:"—", status:"Pending", flagged:false, result:null },
      { candidate:"David Ade",    employer:"—", status:"Pending", flagged:false, result:null },
      { candidate:"Mary Johnson", employer:"—", status:"Pending", flagged:false, result:null },
    ],
  },
  "cpb3-Employment Reference": {
    released: true,
    tasks: [
      { candidate:"John Doe",     employer:"Acme Corporation", status:"Complete", flagged:false,
        result:{ outcome:"Verified", positionClaimed:"Senior Software Engineer", positionVerified:"Senior Software Engineer", periodClaimed:"Jan 2020 – Dec 2023", periodVerified:"Jan 2020 – Dec 2023", contact:"Jane HR (jane@acme.ng)", verifiedOn:"22 Feb 2026", notes:"Employment confirmed with positive reference." } },
      { candidate:"Jane Smith",   employer:"Beta Industries",  status:"Complete", flagged:false,
        result:{ outcome:"Verified", positionClaimed:"Marketing Lead", positionVerified:"Marketing Lead", periodClaimed:"Mar 2019 – Nov 2023", periodVerified:"Mar 2019 – Nov 2023", contact:"HR Dept (hr@beta.ng)", verifiedOn:"22 Feb 2026", notes:"All details confirmed." } },
      { candidate:"Mike Brown",   employer:"Gamma Holdings",   status:"Complete", flagged:true,
        result:{ outcome:"Discrepancy", positionClaimed:"Senior Manager", positionVerified:"Manager", periodClaimed:"Jan 2018 – Dec 2022", periodVerified:"Jan 2018 – Dec 2022", contact:"Bob HR (bob@gamma.ng)", verifiedOn:"22 Feb 2026", notes:"Job title mismatch noted. Client accepted employer's version." } },
      { candidate:"Sarah Green",  employer:"Delta Corp",       status:"Complete", flagged:false,
        result:{ outcome:"Verified", positionClaimed:"Analyst", positionVerified:"Analyst", periodClaimed:"Jun 2020 – Aug 2023", periodVerified:"Jun 2020 – Aug 2023", contact:"HR (hr@delta.ng)", verifiedOn:"21 Feb 2026", notes:"All details verified." } },
      { candidate:"Peter Obi",    employer:"Echo Limited",     status:"Complete", flagged:false,
        result:{ outcome:"Verified", positionClaimed:"Developer", positionVerified:"Developer", periodClaimed:"Feb 2021 – Jan 2024", periodVerified:"Feb 2021 – Jan 2024", contact:"Admin (admin@echo.ng)", verifiedOn:"21 Feb 2026", notes:"Confirmed." } },
      { candidate:"Grace Lee",    employer:"Foxtrot Inc",      status:"Complete", flagged:false,
        result:{ outcome:"Verified", positionClaimed:"Officer", positionVerified:"Officer", periodClaimed:"Apr 2020 – Dec 2023", periodVerified:"Apr 2020 – Dec 2023", contact:"HR (hr@foxtrot.ng)", verifiedOn:"20 Feb 2026", notes:"Confirmed." } },
    ],
  },
};
